[build]
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"
  # Exclude React environment variables from secrets scanning
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_AUTH0_DOMAIN,REACT_APP_AUTH0_CLIENT_ID,REACT_APP_SUPABASE_URL,REACT_APP_SUPABASE_ANON_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/static/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  GENERATE_SOURCEMAP = "false"